version: '2'
services:
  dokuwiki:
    image: 'bitnami/dokuwiki:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - 'dokuwiki_data:/bitnami'
volumes:
  dokuwiki_data:
    driver: local
